pluginDescription=A plugin that replaces any message on your server, to the receiver's language, in real time!
pluginWebsite=https://triton.rexcantor64.com/
pluginAuthor=Rexcantor64
pluginApiVersion=1.13
pluginName=Triton

systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
systemProp.http.ssl.insecure=true
systemProp.http.ssl.allowall=true
systemProp.http.ssl.ignore.validity.dates=true